%this script plots the domain wall based on input file in the OVF format
%which can be generated by softwares linke mumax3 etc.
clear all;close all;clc
%% values can be tuned for visualization
%interval of plot along x direction,
%e.g., if xmesh=512 and xplotstep=32, then m is plotted as #1,17, 33...
%along the horizontal direction
xplotstep=32;
%interval of plot along y direction
%e.g., if ymesh=30 and yplotstep=6, then m is plotted as #1,6, 11...
%along the longitudinal direction
yplotstep=6;
plot2dflg=1;%plot DW in 2D
plot3dflg=0;%plot DW in 3D
scale2d=0.3;%scale factor of the arrow size in 2D plot
scale3d=1;%scale factor of the arrow size in 3D plot
xlimminplot=80;
xlimmaxplot=200;
ylimminplot=70;
ylimmaxplot=80;
plotip=0;%0:plot in-plane magnet; 1:plot perpendicular magnet,
%modify to differentiate i-Bloch, i-Neel, p-Bloch, p-Neel
generatemovie=0;
findDWcenter=0;
ticknum=6;
%datname=sprintf('m%0.6d.ovf',datrange(ctdat));
datname=sprintf('relaxed_m.ovf');
%% values from mx3 file
xmesh=512;%command gridsize(xmesh,ymesh,zmesh) in mumax3
ymesh=30;
zmesh=1;
cellsizex=4;%command setcellsize(cellsizex,cellsizey,cellsizez) in mumax3
cellsizey=4;
%% processed values for visualization, don't modify
xmin=0;
ymin=0;
xmax=xmesh*cellsizex;
ymax=ymesh*cellsizey;
xmaxplot=ymax*2;%2 is an arbitary number, just to show x size is larger than y
ymaxplot=ymax;
xscal=xmax/xmaxplot;
yscal=ymax/ymaxplot;
tmp1=round(xmaxplot/ticknum);
tmp2=round(xmax/ticknum);
xtickk=[0,linspace(tmp1,tmp1*ticknum,ticknum)];
xticklabell=[0,linspace(tmp2,tmp2*ticknum,ticknum)];
clear tmp1 tmp2
%% load the data
if (1)
    % Read the file
    fid = fopen(datname,'r');
    str = textscan(fid,'%s','Delimiter','\n');
    fclose(fid);
    % skip the first 29 lines and load the rest data
    % you might need to check if other softwares is also 29 lines
    str2 = str{1}(30:xmesh*ymesh*zmesh+29);
    % Save as a text file
    fid2 = fopen('test.txt','w');
    fprintf(fid2,'%s\n', str2{:});
    fclose(fid2);
end
dattt=importdata('test.txt');
delete test.txt

%% plott
[X,Y,Z,u,v,k]=dwplot(xmesh,ymesh,zmesh,xmin,xmaxplot,cellsizex,xplotstep,ymin,ymaxplot,cellsizey,yplotstep,dattt,plotip,plot2dflg,plot3dflg,scale2d,scale3d);
if plot2dflg
    view(0,90)
    set(gca,'XTick',xtickk)
    set(gca,'XTickLabel',xticklabell)
    xlabel('length(nm)');ylabel('width(nm)');
    xlim([xlimminplot xlimmaxplot]);ylim([ylimminplot ylimmaxplot]*1.2);
elseif plot3dflg
    figure;
    quiver3(X,Y,Z,u,v,k,scale3d)
end

%% generate movie
if generatemovie
    titlename=sprintf('title');
    M(ctdat) = getframe(gcf);
    
    %add the following out of loop
    %{
    if generatemovie
    clear ctdat
    figure
    movie(M)
    v=VideoWriter('myavi.avi')
    open(v)
    writeVideo(v,M)
    end
    %}
end
%% find DW center
if findDWcenter
    %modify to diffentiate different DW
    [maxy,indicc]=max(abs(v),[],2);
    middle_row=round((ymesh/yplotstep)/2);
    max_column_number=indicc(middle_row);
    DWposition(ctdat)=X(middle_row,max_column_number);%[nm]
end